<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="PC-20180201HBWK" name="Test" tests="2" failures="1" timestamp="18 Mar 2019 15:00:20 GMT" time="0.03" errors="0">
  <testcase name="test_01" time="0.006" classname="Se_2019.test_ng_01">
    <failure type="java.lang.AssertionError" message="expected [3] but found [2]">
      <![CDATA[java.lang.AssertionError: expected [3] but found [2]
	at Se_2019.test_ng_01.test_01(test_ng_01.java:17)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- test_01 -->
  <testcase name="test_02" time="0.002" classname="Se_2019.test_ng_01"/>
</testsuite> <!-- Test -->
